import { TicketsTable } from "@/components/tickets/TicketsTable";

export default function TicketsPage() {
  return (
    <div className="p-8">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-3xl font-h1 font-bold text-on-background">My Tickets</h1>
          <p className="text-on-surface-variant font-body-md mt-1">View your support tickets generated by EmVoice.</p>
        </div>
      </div>

      <TicketsTable />
    </div>
  );
}
